[package]
name = "zish_rust"
version = "0.1.0"
authors = ["Tony Locke <tlocke@tlocke.org.uk>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
regex = "1.1.2"
chrono = "0.4.6"
bigdecimal = "0.0.15"
